repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: end-of-file-fixer
        exclude: ^test/problems/.*/data/
    -   id: trailing-whitespace
        exclude: ^test/problems/.*/data/
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        pass_filenames: false
        entry: "mypy --package bapctools"
        language: system
        require_serial: true # don't split filenames into multiple processes
        exclude: ^(bapctools/resources|bin/misc|test)/
